server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:~/mmatejakti;AUTO_SERVER=TRUE
#    url: jdbc:h2:mem:mmatejakti
    username: sa
    password: password
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: never
      platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: twoj_email
    password: twoje_haslo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
