server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: true
        web-allow-others: true
  datasource:
    url: jdbc:h2:file:~/mmatejakti;AUTO_SERVER=TRUE
    username: sa
    password: password
    driverClassName: org.h2.Driver
    platform: h2
    initialization-mode: NEVER
#    initialization-mode: never
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
#      It's some problem with cascade drop db
#      ddl-auto: create-drop
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: twoj_email
    password: twoje_haslo
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
