### Get all notifications
GET {{host}}/api/notifications/all

### Add notificationEntity
POST {{host}}/api/notifications/add
Content-Type: application/json

{
  "description": "Mam problem",
  "service": "WEZWANIE_ASSISTANCE",
  "client": {
    "email": "qwe1@wp.pl",
    "name": "Jurij",
    "surname": "Owsienko",
    "phoneNumber": "123123123"
  },
  "address": {
    "postCode": "123123",
    "town": "Radom",
    "street": "Koniec",
    "streetNumber": "123"
  }
}

###
